package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "customerpayment")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Customerpayment {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the customerpayment table
    private Integer id;


    @Column(name = "billno")
    @Basic(optional = false)
    private String billno;


    @Column(name = "reservationamount")
    @Basic(optional = false)
    private BigDecimal reservationamount;

    @Column(name = "currentamount")
    @Basic(optional = false)
    private BigDecimal currentamount;

    @Column(name = "paidamount")
    @Basic(optional = false)
    private BigDecimal paidamount;

    @Column(name = "balanceamount")
    @Basic(optional = false)
    private BigDecimal balanceamount;

    @Column(name = "paiddatetime")
    @Basic(optional = false)
    private LocalDateTime paiddatetime;

    @Column(name = "depositeddatetime")
    @Basic(optional = false)
    private LocalDateTime depositeddatetime;

    @Column(name = "description")
    @Basic(optional = true)
    private String description;

    @Column(name = "remark")
    @Basic(optional = false)
    private String remark;

    @Column(name = "transferid")
    @Basic(optional = false)
    private String transferid;

    @Column(name = "bankname")
    @Basic(optional = false)
    private String bankname;

    @Column(name = "transferaccname")
    @Basic(optional = false)
    private String transferaccname;

    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "cpstatus_id", referencedColumnName = "id")
    private CPstatus cpstatus_id;

    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "cpmethod_id", referencedColumnName = "id")
    private Cpmethod cpmethod_id;

    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "reservation_id", referencedColumnName = "id")
    private Reservation reservation_id;

    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "employee_id", referencedColumnName = "id")
    private Employee employee_id;

    public Customerpayment(String billno) {
        this.billno = billno;
    }


}


