package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Table(name = "customerstatus")
//map Customer status class to the customer status table

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Customerstatus {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //not null
    @Column(name = "id")
    //map id attribute to the column name of the customer status table
    private Integer id;

    @Column(name = "name")
    @Basic(optional = false)
    private  String name;
}
