package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import javax.persistence.*;
import java.time.LocalDate;

@Entity
//To convert Persistance entity: map class with the db table
@Table(name = "customer")
//map Customer class to the customer table
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Customer {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //not null
    @Column(name = "id")
    //map id attribute to the column name of the customer table
    private Integer id;


    @Column(name = "regno")
    @Basic(optional = false)
    private  String regno;

    @Column(name = "fname")
    @Basic(optional = false)
    private String fname;

    @Column(name = "lname")
    @Basic(optional = false)
    private  String lname;

    @Column(name = "mobileno")
    @Basic(optional = false)
    private String mobileno;

    @Column(name = "secondno")
    @Basic(optional = true)
    private String secondno;

    @Column(name = "nic")
    @Basic(optional = true)
    private String nic;

    @Column(name = "address")
    @Basic(optional = false)
    private String address;

    @Column(name ="description")
    @Basic(optional = false)
    private String description;

    @Column(name = "addeddate")
    @Basic(optional = false)
    private LocalDate addeddate;




    @JoinColumn(name="customerstatus_id",referencedColumnName = "id")
    @ManyToOne(optional = false,fetch=FetchType.EAGER)
    private Customerstatus customerstatus_id;



    @JoinColumn(name="employee_id",referencedColumnName = "id")
    @ManyToOne(optional = false,fetch=FetchType.EAGER)
    private Employee employee_id;

    public Customer(String regno){
        this.regno=regno;
    }

    public Customer(Integer id,String fname,String lname,String mobileno,String address){
        this.id=id;
        this.fname=fname;
        this.lname=lname;
        this.mobileno=mobileno;
        this.address=address;


    }
}
