package com.gamagerestaurant.model;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;

@Entity
@Table(name= "dailyremove")
@Data
@NoArgsConstructor
@AllArgsConstructor

public class Dailyremove {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the dailyremove table
    private Integer id;


    @Basic(optional = false)
    @Column(name = "dailyremovecode")
    private String dailyremovecode;

    @Basic(optional = false)
    @Column(name = "removeqty")
    private BigDecimal removeqty;

    @Basic(optional = false)
    @Column(name = "dailyremovedate")
    private LocalDate dailyremovedate;

    @Basic(optional = true)
    @Column(name = "description")
    private String description;

    @JoinColumn(name = "material_id", referencedColumnName = "id")
    @OneToOne(optional = false,fetch = FetchType.EAGER )
    private Material material_id;

    @JoinColumn(name = "removereason_id", referencedColumnName = "id")
    @ManyToOne(optional = false,fetch = FetchType.EAGER )
    private Removereason removereason_id;

    @JoinColumn(name = "employee_id", referencedColumnName = "id")
    @ManyToOne(optional = false,fetch = FetchType.EAGER )
    private Employee employee_id;

    @JoinColumn(name = "dailyremovestatus_id", referencedColumnName = "id")
    @ManyToOne(optional = false,fetch = FetchType.EAGER )
    private Dailyremovestatus dailyremovestatus_id;


    public Dailyremove( String dailyremovecode){

        this.dailyremovecode=dailyremovecode;
    }

}
