package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Entity
@Data
@Table(name = "grn")
@AllArgsConstructor
@NoArgsConstructor

public class Grn{

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //not null
    @Column(name = "id")
    //map id attribute to the column name of the customer table
    private Integer id;

    @Column(name="grncode")
    @Basic(optional = false)
    private String grncode;

    @Column(name="supplierinvoiceno")
    @Basic(optional = false)
    private String supplierinvoiceno;

    @Column(name="receiveddate")
    @Basic(optional = false)
    private LocalDate receiveddate;

    @Column(name="totalamount")
    @Basic(optional = false)
    private BigDecimal totalamount;

    @Column(name="discountratio")
    @Basic(optional = false)
    private BigDecimal discountratio;

    @Column(name="nettotal")
    @Basic(optional = false)
    private BigDecimal nettotal;

    @Column(name="addeddate")
    @Basic(optional = false)
    private LocalDate addeddate;

    @Column(name="description")
    @Basic(optional = false)
    private String description;


    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "grnstatus_id", referencedColumnName = "id")
    private Grnstatus grnstatus_id;


    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "employee_id", referencedColumnName = "id")
    private Employee employee_id;


    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "porder_id", referencedColumnName = "id")
    private Purchaseorder porder_id;

    @OneToMany(cascade =CascadeType.ALL,mappedBy ="grn_id" ,fetch = FetchType.LAZY, orphanRemoval = true)
    private List<GrnHasMaterial>grnHasMaterialList;

    public  Grn(Integer id,String grncode){
        this.id=id;
        this.grncode=grncode;
    }

    public Grn(String grncode){
        this.grncode = grncode;
    }
}