package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDate;

@Entity
@Table(name= "material")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Material {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the material table
    private Integer id;


    @Basic(optional = false)
    @Column(name = "materialcode")
    private String materialcode;

    @Basic(optional = false)
    @Column(name = "materialname")
    private String materialname;

    @Basic(optional = false)
    @Column(name = "addeddate")
    private LocalDate addeddate;

    @Basic(optional = false)
    @Column(name = "description")
    private String description;

    @Basic(optional = false)
    @Column(name = "unitsize")
    private Integer unitsize;

    @JoinColumn(name = "materialstatus_id", referencedColumnName = "id")
    @OneToOne(optional = false,fetch = FetchType.EAGER )
    private Materialstatus materialstatus_id;

    @JoinColumn(name = "materialcategory_id", referencedColumnName = "id")
    @ManyToOne(optional = false,fetch = FetchType.EAGER )
    private Materialcategory materialcategory_id;

    @JoinColumn(name = "unittype_id", referencedColumnName = "id")
    @ManyToOne(optional = false,fetch = FetchType.EAGER )
    private Unittype unittype_id;


    public Material(Integer id,String materialcode, String materialname){
        this.id=id;
        this.materialcode=materialcode;
        this.materialname=materialname;

    }
    public Material(String materialcode){

        this.materialcode=materialcode;

    }

    }