package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;

@Entity
@Table(name= "materialinventory")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Materialinventory {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the materialinventory table
    private Integer id;


    @Basic(optional = false)
    @Column(name = "avaqty")
    private BigDecimal avaqty;

    @Basic(optional = false)
    @Column(name = "totalqty")
    private BigDecimal totalqty;

    @Basic(optional = false)
    @Column(name = "removeqty")
    private BigDecimal removeqty;

    @JoinColumn(name = "material_id", referencedColumnName = "id")
    @OneToOne(optional = false,fetch = FetchType.EAGER )
    private Material material_id;

    @JoinColumn(name = "inventorystatus_id", referencedColumnName = "id")
    @ManyToOne(optional = false,fetch = FetchType.EAGER )
    private Inventorystatus inventorystatus_id;
}
