package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Entity
@Data
@Table(name = "menu")
@AllArgsConstructor
@NoArgsConstructor
public class Menu {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //not null
    @Column(name = "id")
    //map id attribute to the column name of the customer table
    private Integer id;

    @Column(name="menucode")
    @Basic(optional = false)
    private String menucode;

    @Column(name="menuname")
    @Basic(optional = false)
    private String menuname;

    @Column(name="addeddate")
    @Basic(optional = false)
    private LocalDate addeddate;

    @Column(name="description")
    @Basic(optional = false)
    private String description;

    @Column(name="price")
    @Basic(optional = false)
    private BigDecimal price;


    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "menustatus_id", referencedColumnName = "id")
    private Menustatus menustatus_id;

    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "menucategory_id", referencedColumnName = "id")
    private Menucategory menucategory_id;

    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "employee_id", referencedColumnName = "id")
    private Employee employee_id;



    @OneToMany(cascade =CascadeType.ALL,mappedBy ="menu_id" ,fetch = FetchType.LAZY, orphanRemoval = true)
    private List<MenuHasSubmenu> menuHasSubmenuList;


    public Menu(Integer id, String menucode ,BigDecimal price,String menuname){
        this.id=id;
        this.menucode=menucode;
        this.price=price;
        this.menuname=menuname;
    }

    public Menu(String menucode){

        this.menucode=menucode;
    }
}
