package com.gamagerestaurant.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;

@Entity
@Table(name="porder_has_material")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PurchaseorderHasMaterial {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the porder_has_material table
    private Integer id ;

    @Column(name="purchaseprice")
    @Basic(optional = false)
    private BigDecimal purchaseprice;

    @Column(name="qty")
    @Basic(optional = false)
    private BigDecimal qty;

    @Column(name="linetotal")
    @Basic(optional = false)
    private BigDecimal linetotal;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="porder_id",referencedColumnName ="id")
    @JsonIgnore
    private Purchaseorder porder_id;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="material_id",referencedColumnName ="id")
    private Material material_id ;

    public PurchaseorderHasMaterial(Integer id){
        this.id=id;

    }

}
