package com.gamagerestaurant.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;

@Entity
@Table(name="quotation_has_material")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class QuotationHasMaterial {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the quotationhasmaterial table
    private Integer id ;

    @Column(name="purchaseprice")
    @Basic(optional = false)
    private BigDecimal purchaseprice;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="quotation_id",referencedColumnName ="id")
    @JsonIgnore
    private Quotation quotation_id;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="material_id",referencedColumnName ="id")
    private Material material_id ;
}
