package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.List;

@Entity
@Table(name="quotation")
@Data
//@Data- generate setters getters to axcess data
@NoArgsConstructor
@AllArgsConstructor
public class Quotation {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the quotation table
    private Integer id ;

    @Column(name="quotationcode")
    @Basic(optional = false)
    private  String quotationcode;

    @Column(name="receiveddate")
    @Basic(optional = false)
    private LocalDate receiveddate ;

    @Column(name="validfrom")
    @Basic(optional = false)
    private LocalDate validfrom;

    @Column(name="validto")
    @Basic(optional = false)
    private LocalDate validto;

    @Column(name="description")
    @Basic(optional = true)
    private String description;

    @Column(name="addeddate")
    @Basic(optional = false)
    private LocalDate addeddate;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="quotationrequest_id",referencedColumnName ="id")
    private QuotationRequest quotationrequest_id;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="quotationstatus_id",referencedColumnName ="id")
    private Quotationstatus quotationstatus_id;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="employee_id",referencedColumnName ="id")
    private Employee employee_id ;

    @OneToMany(cascade =CascadeType.ALL,mappedBy = "quotation_id" ,fetch = FetchType.LAZY, orphanRemoval = true)
    private List<QuotationHasMaterial> quotationHasMaterialList;

    public Quotation(Integer id,String quotationcode){
        this.id=id;
        this.quotationcode=quotationcode;
    }


    public Quotation(String quotationcode){

        this.quotationcode=quotationcode;
    }


}
