package com.gamagerestaurant.model;


import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDate;

@Entity
@Table(name="quotationrequest")
@Data
@NoArgsConstructor
@AllArgsConstructor

public class QuotationRequest {
    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the quotationrequest table
    private Integer id;


    @Column(name="qrcode")
    @Basic(optional = false)
    private String qrcode;


    @Column(name="requireddate")
    @Basic(optional = false)
    private LocalDate requireddate;


    @Column(name="addeddate")
    @Basic(optional = false)
    private LocalDate addeddate;


    @Column(name="description")
    @Basic(optional = false)
    private String description;


    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="qrstatus_id",referencedColumnName ="id")
    private QrStatus qrstatus_id;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="employee_id",referencedColumnName ="id")
    private Employee employee_id;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="supplier_id",referencedColumnName ="id")
    private Supplier supplier_id;

    public QuotationRequest(Integer id,String qrcode,Supplier supplier_id){
        this.id=id;
        this.qrcode=qrcode;
        this.supplier_id=supplier_id;
    }

    public QuotationRequest(String qrcode){
               this.qrcode=qrcode;

    }
    public QuotationRequest(Integer id,String qrcode){
        this.id=id;
        this.qrcode=qrcode;

    }

}
