package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Table(name = "registeredcustomer")
//map Customer class to the customer table
@Data
@AllArgsConstructor
@NoArgsConstructor
public class RegisteredCustomer {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //not null
    @Column(name = "id")
    //map id attribute to the column name of the customer table
    private Integer id;


    @Column(name = "regno")
    @Basic(optional = false)
    private  String regno;
}
