package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;

@Entity
@Table(name="service")
@Data
@AllArgsConstructor
@NoArgsConstructor

public class Service {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the supplier table
    private Integer id;

    @Column(name="servicecode")
    @Basic(optional = false)
    private String servicecode;

    @Column(name="servicename")
    @Basic(optional = false)
    private String servicename;

    @Column(name="servicecharge")
    @Basic(optional = false)
    private BigDecimal servicecharge;

    @Column(name="addeddate")
    @Basic(optional = false)
    private LocalDate addeddate;


    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="service_status_id",referencedColumnName ="id")
    private Servicestatus service_status_id;


    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="employee_id",referencedColumnName ="id")
    private Employee employee_id;

    public  Service(Integer id,String servicecode, String servicename){
        this.id=id;
        this.servicecode=servicecode;
        this.servicename=servicename;
    }


}
