package com.gamagerestaurant.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;

@Entity
@Table(name="submenu_has_material")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class SubmenuHasMaterial {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the grn_has_material table
    private Integer id ;


    @Column(name="qty")
    @Basic(optional = false)
    private BigDecimal qty;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="submenu_id",referencedColumnName ="id")
    @JsonIgnore
    private Submenu submenu_id;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="material_id",referencedColumnName ="id")
    private Material material_id ;
}
