package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Entity
@Data
@Table(name = "submenu")
@AllArgsConstructor
@NoArgsConstructor
public class Submenu {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //not null
    @Column(name = "id")
    //map id attribute to the column name of the customer table
    private Integer id;

    @Column(name="submenucode")
    @Basic(optional = false)
    private String submenucode;

    @Column(name="submenuname")
    @Basic(optional = false)
    private String submenuname;

    @Column(name="addeddate")
    @Basic(optional = false)
    private LocalDate addeddate;

    @Column(name="description")
    @Basic(optional = false)
    private String description;

    @Column(name="price")
    @Basic(optional = false)
    private BigDecimal price;



    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "submenucategory_id", referencedColumnName = "id")
    private Submenucategory submenucategory_id;

    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "submenustatus_id", referencedColumnName = "id")
    private Submenustatus submenustatus_id;

    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "employee_id", referencedColumnName = "id")
    private Employee employee_id;

    @OneToMany(cascade =CascadeType.ALL,mappedBy ="submenu_id" ,fetch = FetchType.LAZY, orphanRemoval = true)
    private List<SubmenuHasMaterial> submenuHasMaterialList;


    public  Submenu(Integer id,String submenucode,BigDecimal price,String submenuname){
        this.id=id;
        this.submenucode=submenucode;
        this.price=price;
        this.submenuname=submenuname;
    }

    public  Submenu(String submenucode ){

        this.submenucode=submenucode;

    }
}
