package com.gamagerestaurant.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

@Entity
@Table(name="supplier")
@Data
@NoArgsConstructor
@AllArgsConstructor

//ignore null values is supplier arreas  report
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Supplier {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the supplier table
    private Integer id;

    @Column(name="regno")
    @Basic(optional = false)
    private String regno;

    @Column(name="fullname")
    @Basic(optional = false)
    private String fullname;

    @Column(name="contactno1")
    @Basic(optional = false)
    private String contactno1;

    @Column(name="cpname")
    @Basic(optional = false)
    private String cpname;

    @Column(name="contactno2")
    @Basic(optional = true)
    private Integer contactno2;

    @Column(name="email")
    @Basic(optional = false)
    private String email;

    @Column(name="address")
    @Basic(optional = false)
    private String address;


    @Column(name="addeddate")
    @Basic(optional = false)
    private LocalDate addeddate;

    @Column(name="description")
    @Basic(optional = true)
    private String description;

    @Column(name="bankholdername")
    @Basic(optional = true)
    private String bankholdername;

    @Column(name="bankname")
    @Basic(optional = true)
    private String  bankname;

    @Column(name="bankbranchname")
    @Basic(optional =true)
    private String bankbranchname;

    @Column(name="bankaccountno")
    @Basic(optional = true)
    private Integer bankaccountno;

    @Column(name="arreasamount")
    @Basic(optional = true)
    private BigDecimal arreasamount;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="supplierstatus_id",referencedColumnName ="id")
    private Supplierstatus supplierstatus_id;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="employee_id",referencedColumnName ="id")
    private Employee employee_id;

    @OneToMany(cascade =CascadeType.ALL,mappedBy = "supplier_id" ,fetch = FetchType.LAZY, orphanRemoval = true)
    private List<Supplierhasmaterial> supplierhasmaterialList;

    public  Supplier(Integer id,String regno,String fullname){
        this.id=id;
        this.regno=regno;
        this.fullname=fullname;
    }

    public Supplier(String regno){

                this.regno=regno;
    }

    public Supplier(String fullname,BigDecimal arreasamount){

        this.fullname=fullname;
        this.arreasamount=arreasamount;
    }

    }


