package com.gamagerestaurant.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Table(name="supplier_has_material")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Supplierhasmaterial {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the supplierhasmaterial table
    private Integer id;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="supplier_id",referencedColumnName ="id")
    @JsonIgnore
    private Supplier supplier_id;

    @ManyToOne(optional = false,fetch = FetchType.EAGER)
    @JoinColumn(name="material_id",referencedColumnName ="id")
    private Material material_id;

}
