package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Table(name="supplierstatus")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Supplierstatus {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the supplierstatus table
    private Integer id;

    @Column(name="name")
    @Basic(optional = false)
    private String name;
}
