package com.gamagerestaurant.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Data
@Table(name = "tableallocation_has_tableddetail")
@AllArgsConstructor
@NoArgsConstructor

public class TableallocationHasTableddetail {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //not null
    @Column(name = "id")
    //map id attribute to the column name of the customer table
    private Integer id;


    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "tableallocation_id", referencedColumnName = "id")
    @JsonIgnore
    private Tableallocation tableallocation_id;

    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "tableddetail_id", referencedColumnName = "id")
    private Tabledetail tableddetail_id;
}

