package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Data
@Table(name = "tableddetail")
@AllArgsConstructor
@NoArgsConstructor
public class Tabledetail {
    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //Not Null
    @Column(name = "id")
    //map id attribute to the column name of the tabledetail table
    private Integer id;


    @Basic(optional = false)
    @Column(name = "tableallcode")
    private String tableallcode;

    @Basic(optional = false)
    @Column(name = "tablename")
    private String tablename;

    @Basic(optional = false)
    @Column(name = "nofchairs")
    private Integer nofchairs;


}
