package com.gamagerestaurant.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@Entity
@Data
@Table(name = "tableallocation")
@AllArgsConstructor
@NoArgsConstructor

public class Tableallocation {

    @Id
    //define Id as primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //autogenerated value
    @Basic(optional = false)
    //not null
    @Column(name = "id")
    //map id attribute to the column name of the customer table
    private Integer id;

    @Column(name="tableallocationcode")
    @Basic(optional = false)
    private String tableallocationcode;

    @Column(name="reserveddate")
    @Basic(optional = false)
    private LocalDate reserveddate;

    @Column(name="reservetime")
    @Basic(optional = false)
    private LocalTime reservetime;

    @Column(name="addeddate")
    @Basic(optional = false)
    private LocalDate addeddate;


    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "tablestatus_id", referencedColumnName = "id")
    private Tablestatus tablestatus_id;


    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumn(name = "reservation_id", referencedColumnName = "id")
    private Reservation reservation_id;

    @OneToMany(cascade =CascadeType.ALL,mappedBy = "tableallocation_id" ,fetch = FetchType.LAZY, orphanRemoval = true)
    private List<TableallocationHasTableddetail> tableallocationHasTableddetailList;


    public Tableallocation(String tableallocationcode){
        this.tableallocationcode = tableallocationcode;
    }

}